alias extip='dig +short myip.opendns.com @resolver1.opendns.com'
alias vc='virsh console'
alias lsday='find -type f -mtime -1 | xargs ls -l'
alias lsweek='find -type f -mtime -7 | xargs ls -l'
alias lsmonth='find -type f -mtime -31 | xargs ls -l'
alias lsyear='find -type f -mtime -366 | xargs ls -l'
